In [1]:
import numpy as np
import torch
from torch import nn

In [2]:
net1=nn.Sequential(
    nn.Linear(30,40),
    nn.ReLU(),
    nn.Linear(40,50),
    nn.ReLU(),
    nn.Linear(50,10)
)

In [3]:
w1=net1[0].weight
b1=net1[0].bias

In [4]:
print(w1)

Parameter containing:
tensor([[-0.0706, -0.0300,  0.0809,  ...,  0.1337, -0.1517, -0.1413],
        [ 0.1603, -0.1201, -0.0126,  ..., -0.0802, -0.1273, -0.1170],
        [ 0.1785,  0.0826,  0.1420,  ...,  0.0677,  0.1163, -0.1700],
        ...,
        [ 0.0409,  0.1592,  0.1117,  ...,  0.0018,  0.0550, -0.0920],
        [ 0.1289,  0.0320,  0.1599,  ...,  0.1045, -0.0394,  0.0304],
        [ 0.0380, -0.1638,  0.1335,  ...,  0.0956,  0.0536,  0.1322]],
       requires_grad=True)


In [5]:
net1[0].weight.data=torch.from_numpy(np.random.uniform(3,5,size=(40,30)))

In [6]:
print(net1[0].weight)

Parameter containing:
tensor([[3.8753, 3.1928, 3.9959,  ..., 4.3677, 4.7646, 3.4888],
        [3.8110, 3.7116, 3.3725,  ..., 3.3414, 3.9001, 3.4464],
        [3.4373, 4.0609, 4.6713,  ..., 4.3985, 4.8385, 4.7497],
        ...,
        [4.2926, 3.7396, 4.9737,  ..., 3.4710, 4.7653, 4.2036],
        [4.5235, 4.8773, 4.8815,  ..., 4.6595, 3.7931, 4.4269],
        [4.8298, 4.6019, 4.3595,  ..., 3.8497, 3.5075, 4.7963]],
       dtype=torch.float64, requires_grad=True)


In [7]:
class sim_net(nn.Module):
    def __init__(self):
        super(sim_net,self).__init__()
        self.l1= nn.Sequential(
            nn.Linear(30,40),
            nn.ReLU()
        )
        self.l1[0].weight.data=torch.randn(40,30)
        self.l2= nn.Sequential(
            nn.Linear(40,50),
            nn.ReLU()
        )
        self.l3= nn.Sequential(
            nn.Linear(50,10),
            nn.ReLU()
        )
    def forward(self,x):
        x=self.l1(x)
        x=self.l2(x)
        x=self.l3(x)
        return x

In [8]:
net2=sim_net()

In [9]:
# 访问 children
for i in net2.children():
    print(i)

Sequential(
  (0): Linear(in_features=30, out_features=40, bias=True)
  (1): ReLU()
)
Sequential(
  (0): Linear(in_features=40, out_features=50, bias=True)
  (1): ReLU()
)
Sequential(
  (0): Linear(in_features=50, out_features=10, bias=True)
  (1): ReLU()
)


In [10]:
# 访问 modules
for i in net2.modules():
    print(i)

sim_net(
  (l1): Sequential(
    (0): Linear(in_features=30, out_features=40, bias=True)
    (1): ReLU()
  )
  (l2): Sequential(
    (0): Linear(in_features=40, out_features=50, bias=True)
    (1): ReLU()
  )
  (l3): Sequential(
    (0): Linear(in_features=50, out_features=10, bias=True)
    (1): ReLU()
  )
)
Sequential(
  (0): Linear(in_features=30, out_features=40, bias=True)
  (1): ReLU()
)
Linear(in_features=30, out_features=40, bias=True)
ReLU()
Sequential(
  (0): Linear(in_features=40, out_features=50, bias=True)
  (1): ReLU()
)
Linear(in_features=40, out_features=50, bias=True)
ReLU()
Sequential(
  (0): Linear(in_features=50, out_features=10, bias=True)
  (1): ReLU()
)
Linear(in_features=50, out_features=10, bias=True)
ReLU()


In [11]:
for layer in net2.modules():
    if isinstance(layer, nn.Linear):
        param_shape = layer.weight.shape
        layer.weight.data = torch.from_numpy(np.random.normal(0, 0.5, size=param_shape))

In [12]:
from torch.nn import init

In [13]:
print(net1[0].weight)

Parameter containing:
tensor([[3.8753, 3.1928, 3.9959,  ..., 4.3677, 4.7646, 3.4888],
        [3.8110, 3.7116, 3.3725,  ..., 3.3414, 3.9001, 3.4464],
        [3.4373, 4.0609, 4.6713,  ..., 4.3985, 4.8385, 4.7497],
        ...,
        [4.2926, 3.7396, 4.9737,  ..., 3.4710, 4.7653, 4.2036],
        [4.5235, 4.8773, 4.8815,  ..., 4.6595, 3.7931, 4.4269],
        [4.8298, 4.6019, 4.3595,  ..., 3.8497, 3.5075, 4.7963]],
       dtype=torch.float64, requires_grad=True)


In [14]:
init.xavier_uniform(net1[0].weight)

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  """Entry point for launching an IPython kernel.


Parameter containing:
tensor([[-0.1370,  0.1829, -0.1048,  ...,  0.0640,  0.2180,  0.1076],
        [-0.2274, -0.0716, -0.0438,  ...,  0.0617, -0.1926, -0.2118],
        [-0.0875,  0.1350, -0.2081,  ..., -0.0903, -0.1176,  0.1613],
        ...,
        [ 0.1258, -0.1652, -0.0627,  ..., -0.1223,  0.2487, -0.2729],
        [-0.0035,  0.0480,  0.1564,  ...,  0.1210, -0.0176, -0.2005],
        [-0.2840, -0.1037,  0.1223,  ...,  0.2567, -0.2167,  0.0614]],
       dtype=torch.float64, requires_grad=True)

In [15]:
print(net1[0].weight)

Parameter containing:
tensor([[-0.1370,  0.1829, -0.1048,  ...,  0.0640,  0.2180,  0.1076],
        [-0.2274, -0.0716, -0.0438,  ...,  0.0617, -0.1926, -0.2118],
        [-0.0875,  0.1350, -0.2081,  ..., -0.0903, -0.1176,  0.1613],
        ...,
        [ 0.1258, -0.1652, -0.0627,  ..., -0.1223,  0.2487, -0.2729],
        [-0.0035,  0.0480,  0.1564,  ...,  0.1210, -0.0176, -0.2005],
        [-0.2840, -0.1037,  0.1223,  ...,  0.2567, -0.2167,  0.0614]],
       dtype=torch.float64, requires_grad=True)
