In [1]:
import torch
from torch.autograd import Variable
from torch import nn

In [2]:
rnn_single=nn.RNNCell(input_size=100,hidden_size=200)

In [5]:
rnn_single.weight_hh.shape

torch.Size([200, 200])

In [6]:
rnn_single.weight_ih.shape

torch.Size([200, 100])

In [7]:
x=Variable(torch.randn(6,5,100))

In [8]:
h_t=Variable(torch.zeros(5,200))

In [9]:
out=[]
for i in range(6):
    h_t=rnn_single(x[i],h_t)
    out.append(h_t)

In [10]:
h_t

tensor([[ 2.3049e-01, -3.7448e-01,  3.8995e-01,  5.6883e-01, -3.7717e-01,
          3.2800e-01,  4.5873e-01, -7.6504e-01, -3.2216e-01, -4.4159e-01,
         -1.5326e-02, -4.5751e-01, -7.5020e-01,  5.8662e-01, -3.3517e-01,
         -3.7511e-03, -7.6874e-01, -1.9210e-01, -7.6924e-01,  7.3015e-01,
          4.2375e-01, -3.4525e-01,  4.2969e-03,  2.9923e-03, -5.6190e-02,
         -6.3093e-01,  4.9243e-01, -9.0754e-02,  3.4371e-01,  2.2830e-01,
         -2.7701e-01, -5.3267e-01, -5.6441e-01,  3.3922e-01, -3.2895e-01,
         -2.1189e-01,  5.3693e-02, -4.7074e-01,  1.0193e-01,  1.7038e-01,
          2.0283e-01,  4.3159e-01,  2.4787e-01, -4.9014e-01,  9.7461e-02,
         -3.7926e-01,  1.5933e-01,  2.2767e-01, -2.8670e-01, -1.2540e-01,
          2.8555e-01,  6.4337e-01,  1.2106e-01,  5.3880e-02, -4.9969e-01,
         -2.5100e-01,  3.4167e-02, -4.7852e-01,  5.5048e-03, -5.5163e-01,
          4.8101e-01, -1.2073e-02,  6.4770e-01, -1.5527e-01,  2.0695e-01,
         -1.5137e-01,  1.4761e-02, -2.

In [11]:
len(out)

6

In [12]:
out[0].shape

torch.Size([5, 200])

In [13]:
rnn_seq=nn.RNN(100,200)

In [15]:
rnn_seq.weight_hh_l0.shape

torch.Size([200, 200])

In [16]:
out,h_t=rnn_seq(x)

In [19]:
h_t.shape

torch.Size([1, 5, 200])

In [20]:
len(out)

6

In [21]:
# 自己定义初始的隐藏状态
h_0 = Variable(torch.randn(1, 5, 200))

In [22]:
out, h_t = rnn_seq(x, h_0)

In [23]:
h_t

tensor([[[ 0.4975,  0.2014,  0.2963, -0.0671,  0.4898,  0.4122,  0.1131,
          -0.4868,  0.0672,  0.0722,  0.4731, -0.7403,  0.4455,  0.0698,
           0.4221,  0.3332, -0.1944,  0.1490,  0.5683,  0.3852, -0.0618,
          -0.0354, -0.1185, -0.5755, -0.1990, -0.0404,  0.2490,  0.3746,
           0.4910,  0.7268, -0.0145,  0.0751, -0.5174, -0.1302, -0.1849,
          -0.1866, -0.6702,  0.2935,  0.4060, -0.1070,  0.5840, -0.3132,
          -0.3578,  0.2207, -0.4100,  0.1512,  0.4147,  0.1713,  0.0133,
           0.2660, -0.6957, -0.0932,  0.7187, -0.0497, -0.2390,  0.2467,
          -0.0076,  0.3872,  0.5211, -0.2013, -0.0874, -0.0477, -0.0547,
          -0.1717, -0.1173,  0.0841, -0.6210, -0.2394, -0.2271, -0.4379,
          -0.3649, -0.0565, -0.4320,  0.2514,  0.5182, -0.4754, -0.2270,
           0.6547, -0.2441,  0.3971, -0.1315, -0.1294,  0.1598,  0.0672,
           0.3483,  0.5635, -0.0251, -0.2558,  0.1922, -0.6197,  0.4004,
           0.0747, -0.4747,  0.7397, -0.4133, -0.32

In [24]:
out.shape

torch.Size([6, 5, 200])

In [25]:
lstm_seq=nn.LSTM(50,100,num_layers=2)# 输入维度 100，输出 200，两层

In [26]:
lstm_seq.weight_hh_l0.shape

torch.Size([400, 100])

In [27]:
lstm_seq.weight_ih_l0.shape

torch.Size([400, 50])

In [28]:
lstm_seq.weight_hh_l1.shape

torch.Size([400, 100])

In [29]:
lstm_seq.weight_ih_l1.shape

torch.Size([400, 100])

In [30]:
lstm_input = Variable(torch.randn(10, 3, 50)) # 序列 10，batch 是 3，输入维度 50

In [31]:
out, (h, c) = lstm_seq(lstm_input)

In [32]:
h.shape # 两层，Batch 是 3，特征是 100

torch.Size([2, 3, 100])

In [33]:
c.shape

torch.Size([2, 3, 100])

In [34]:
out.shape

torch.Size([10, 3, 100])

In [35]:
h_init = Variable(torch.randn(2, 3, 100))
c_init = Variable(torch.randn(2, 3, 100))

In [36]:
out, (h, c) = lstm_seq(lstm_input, (h_init, c_init))

In [37]:
h.shape

torch.Size([2, 3, 100])

In [38]:
c.shape

torch.Size([2, 3, 100])

In [39]:
out.shape

torch.Size([10, 3, 100])

In [40]:
gru_seq = nn.GRU(10, 20)
gru_input = Variable(torch.randn(3, 32, 10))
out, h = gru_seq(gru_input)

In [41]:
gru_seq.weight_hh_l0

Parameter containing:
tensor([[ 0.1006,  0.0829,  0.0231,  ..., -0.1757, -0.0498,  0.1234],
        [-0.1190, -0.0204, -0.0281,  ...,  0.2076, -0.1188, -0.1013],
        [-0.1060,  0.1131,  0.0005,  ..., -0.0991, -0.2015, -0.1691],
        ...,
        [-0.1801,  0.1520, -0.0828,  ...,  0.1761, -0.0039, -0.0280],
        [-0.0030,  0.0837,  0.2177,  ...,  0.2082,  0.1056,  0.0681],
        [ 0.1425,  0.1697, -0.0265,  ...,  0.1946,  0.0455,  0.0240]],
       requires_grad=True)

In [42]:
h.shape

torch.Size([1, 32, 20])

In [43]:
out.shape

torch.Size([3, 32, 20])